---
title: "Simulation Results: Variable Selection"
author: "Lukas"
date: "`r Sys.time()`"
output: 
  html_document: 
    fig_width: 11
    fig_height: 9
    self_contained: no
    code_folding: hide
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(batchtools)
library(ggplot2)
library(patchwork)
library(dplyr)
library(kableExtra)

reg_name <- "fwel_sim_variableselect"
reg_dir <- here::here("registries", reg_name)
loadRegistry(reg_dir)
```

```{r get-results, cache = TRUE}
res <-  ijoin(reduceResultsDataTable(), flatten(getJobPars()))
nrow(res)/nrow(getJobTable())
nrow(findErrors())/nrow(getJobTable())

res |>
  count(problem, t, thresh)
```


```{r runtime-plot}
getJobTable() |>
  select(time.running, problem) |>
  mutate(time.running = as.double(time.running, units = "secs")) |>
  ggplot(aes(x = problem, y = time.running)) +
  geom_boxplot() +
  labs(
    title = "Job Runtime",
    x = "Setting", y = "Runtime (s)"
  ) +
  theme_minimal()
```
