---
title: "Simulation Results"
author: "Lukas"
date: "`r Sys.Date()`"
output: 
  html_document: 
    fig_width: 11
    fig_height: 9
    self_contained: no
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(batchtools)
library(ggplot2)
library(patchwork)
library(dplyr)

reg_name <- "fwel_simulations"
reg_dir <- here::here("registries", reg_name)
loadRegistry(reg_dir)

# Load helper functions in R/
source(here::here("R/sim_cr.R"))
source(here::here("R/mt_res_tidy_plot.R"))

source(here::here("02-problems.R"))
```

```{r get-results}
res <-  ijoin(reduceResultsDataTable(), flatten(getJobPars()))
nrow(res)/nrow(getJobTable())
nrow(findErrors())/nrow(getJobTable())

res |>
  count(problem, z_scale, z_method, theta)
```


```{r runtime-plot}
getJobTable() |>
  select(time.running, problem) |>
  mutate(time.running = as.double(time.running, units = "secs")) |>
  ggplot(aes(x = problem, y = time.running)) +
  geom_boxplot() +
  labs(
    title = "Job Runtime",
    x = "Setting", y = "Runtime (s)"
  ) +
  theme_minimal()

getJobTable() |>
  select(time.running, problem) |>
  mutate(time.running = as.double(time.running, units = "secs")) |>
  summarize(
    total_s = sum(time.running),
    total_h = total_s/60/60
  )
```

```{r}
res_long <- purrr::map2_df(res$problem, res$result, ~tidy_mt_res(.y, true_effects, problem = .x))

# Need a cleaner solution that's maybe also faster
res_long <- purrr::pmap_dfr(res, ~{
  res_tidy <- tidy_mt_res(..2, true_effects, problem = ..3)
  res_tidy$theta <- ..10
  res_tidy
})

```

```{r, include = FALSE, eval = FALSE}
(plot_bt_res(res_long, true_effects, "sim_a") + plot_bt_res(res_long, true_effects, "sim_b")) /
  (plot_bt_res(res_long, true_effects, "sim_c") + plot_bt_res(res_long, true_effects, "sim_d"))
```


Boxplot for `true-estimated`

```{r}
plot_errors_boxplot <- function(res_long, true_effects, problem, z_method = "original", z_scale = 1, iter_max = 2) {
  res_long |>
    filter(
      # iter == 0 is the glmnet solution, compare that with a given iteration of fwelnet
      iter %in% c(0, !!iter_max), 
      xcol != "Noise", z_method == !!z_method, z_scale %in% !!z_scale) |>
    select(-is_noise, -converged, -xcol) |>
    # join true betas from design tbl for nonzero-effects
    left_join(true_effects, by = c("problem", "beta", "x")) |>
    mutate(
      iter = if_else(iter == 0, "glmnet", "fwelnet_mt"),
      # truth doesn't contain true 0s, manually hacking them in here
      truth = ifelse(is.na(truth), 0, truth),
      error = truth - value,
      # Just for optics
      beta = stringr::str_replace_all(beta, "beta", "Cause "),
      z_scale = paste("Z-scalar:", z_scale),
      theta = paste("theta:", theta)
    ) |>
    filter(.data$problem == !!problem) |> 
    ggplot(aes(x = x, y = error, fill = iter, color = iter)) +
    facet_grid(rows = vars(beta), cols = vars(z_scale, theta)) +
    geom_hline(yintercept = 0, lty = "longdash", size = 1) +
    #geom_jitter(alpha = 0.1, position = position_dodge2(width = .5, preserve = "single")) +
    geom_boxplot(alpha = 0.2) +
    scale_color_brewer(
      palette = "Dark2", aesthetics = c("color", "fill"), 
      labels = c(fwelnet_mt = "Multi-Task fwelnet", glmnet = "Cause-Specific glmnet"),
      name = NULL
    ) +
    labs(
      title = NULL,
      subtitle = sim_labels[[problem]],
      x = NULL, y = "Error (true - estimated)"
    ) +
    theme_minimal(base_size = 16) +
    theme(
      panel.spacing = ggplot2::unit(1, "cm"),
      legend.position = "bottom",
      plot.title.position = "plot"
    )
}
```

### Original `z_method`

```{r error-bp-A}
(pa <- plot_errors_boxplot(res_long, true_effects,  "sim_a", z_scale = 1))

# (pa <- plot_errors_boxplot(res_long, true_effects,  "sim_a", z_scale = 1, iter_max = 1))
# (pa <- plot_errors_boxplot(res_long, true_effects,  "sim_a", z_scale = 1, iter_max = 2))
```

```{r error-bp-B}
(pb <- plot_errors_boxplot(res_long, true_effects,  "sim_b", z_scale = 1))
```

```{r error-bp-C}
(pc <- plot_errors_boxplot(res_long, true_effects,  "sim_c", z_scale = 1))

# (pc <- plot_errors_boxplot(res_long, true_effects,  "sim_c", z_scale = 1, iter_max = 1))
# (pc <- plot_errors_boxplot(res_long, true_effects,  "sim_c", z_scale = 1, iter_max = 2))
```

```{r error-bp-D}
(pd <- plot_errors_boxplot(res_long, true_effects,  "sim_d", z_scale = 1))

# (pd <- plot_errors_boxplot(res_long, true_effects,  "sim_d", z_scale = 1, iter_max = 1)) +
# (pd <- plot_errors_boxplot(res_long, true_effects,  "sim_d", z_scale = 1, iter_max = 2))
```

```{r error-bp-all}
((pa + pb) / (pc + pd)) + 
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")
```

### RMSE ± SD Maybe?

```{r rmse-errorbars-fun}
plot_rmse_errorbars <- function(res_long, true_effects, problem, z_method = "original", z_scale = 1) {
  res_long |>
    filter(iter %in% range(iter), xcol != "Noise", problem == !!problem, z_method == !!z_method, z_scale %in% !!z_scale) |>
    select(-is_noise, -converged, -xcol) |>
    # join true betas from design tbl for nonzero-effects
    left_join(true_effects, by = c("problem", "beta", "x")) |>
    mutate(
      iter = if_else(iter == 0, "glmnet", "fwelnet_mt"),
      # truth doesn't contain true 0s, manually hacking them in here
      truth = ifelse(is.na(truth), 0, truth),
      error = (truth - value),
      # Just for optics
      beta = stringr::str_replace_all(beta, "beta", "Cause "),
      z_scale = paste("Z-scalar:", z_scale),
      theta = paste("theta:", theta)
    ) |>
    group_by(x, iter, beta, z_scale, z_method, problem, theta) |>
    summarize(
      rmse = sqrt(mean(error^2)),
      rmse_sd = sd(error),
      .groups = "drop"
    ) |>
    ggplot(aes(x = x, y = rmse, color = iter, fill = iter)) +
    facet_grid(rows = vars(beta), cols = vars(z_method, z_scale, theta)) +
    geom_errorbar(aes(ymin = rmse - rmse_sd, ymax = rmse + rmse_sd), size = 2, position = "dodge2", width = .5) +
    scale_color_brewer(
      palette = "Dark2", aesthetics = c("color", "fill"),
      labels = c(fwelnet_mt = "Multi-Task fwelnet", glmnet = "Cause-Specific glmnet"),
      name = NULL
    ) +
    labs(
      title = NULL,
      subtitle = sim_labels[[problem]],
      x = NULL, y = "RMSE ± SD"
    ) +
    theme_minimal(base_size = 16) +
    theme(
      panel.spacing = ggplot2::unit(1, "cm"),
      legend.position = "bottom",
      plot.title.position = "plot"
    )
}
```

```{r rmse-errorbars-all}
((plot_rmse_errorbars(res_long, true_effects, "sim_a") + plot_rmse_errorbars(res_long, true_effects, "sim_b")) /
  (plot_rmse_errorbars(res_long, true_effects, "sim_c") + plot_rmse_errorbars(res_long, true_effects, "sim_d"))) +
  plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")
```


## What is theta even

Needs adjusting after introducing theta as a simulation param

```{r plot-theta-lambda, eval = FALSE}
res_long |>
  filter(iter == 2, xcol != "Noise", problem == "sim_c", z_method == "original") |>
  select(-is_noise, -converged, -xcol, -z_method, -iter) |>
  tidyr::pivot_wider(names_from = "beta", values_from = "value") |>
  rename(beta_c1 = beta1, beta_c2 = beta2) |>
  tidyr::pivot_longer(
    cols = matches("(c1$)|(c2$)"), 
    names_to = c("param", "cause"), names_sep = "_", 
    values_to = "val"
  ) |>
  mutate(cause = stringr::str_replace_all(cause, "c", "Cause ")) |>
  filter(param != "beta") |>
  ggplot(aes(x = param, y = val, color = cause, fill = cause)) +
  facet_grid(cols = vars(z_scale, theta), labeller = label_both) +
  geom_boxplot(alpha = .75) +
  scale_y_log10() +
  scale_color_manual(
    values = RColorBrewer::brewer.pal(4, "Dark2")[3:4],
    aesthetics = c("color", "fill")
  ) +
  labs(
    title = sim_labels[["sim_c"]],
    subtitle = "Parameter values after final fwelnet fit",
    color = NULL, fill = NULL,
    x = NULL, y = "Value"
  ) +
  theme_minimal(base_size = 16) +
  theme(legend.position = "top")

res_long |>
  filter(iter == 2, xcol != "Noise", problem == "sim_c", z_method == "original") |>
  select(-is_noise, -converged, -xcol, -z_method, -iter) |>
  tidyr::pivot_wider(names_from = "beta", values_from = "value") |>
  rename(beta_c1 = beta1, beta_c2 = beta2) |>
  tidyr::pivot_longer(
    cols = matches("(c1$)|(c2$)"), 
    names_to = c("param", "cause"), names_sep = "_", 
    values_to = "val"
  ) |>
  mutate(cause = stringr::str_replace_all(cause, "c", "Cause ")) |>
  filter(param != "beta") |>
  group_by(x, z_scale, problem, param, cause) |>
  summarize(val_m = mean(val))
```

