---
title: "Bladder Cancer: Variable Selection / Prediction"
author: "Lukas"
date: "`r Sys.time()`"
output: 
  html_document: 
    fig_width: 11
    fig_height: 9
    self_contained: no
    code_folding: hide
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(batchtools)
library(ggplot2)
library(patchwork)
library(dplyr)
library(kableExtra)
library(data.table)

reg_name <- "fwel_sim_varsel_predict"
reg_dir <- here::here("registries", reg_name)
loadRegistry(reg_dir)

theme_set(
  theme_minimal(base_size = 16) +
  theme(
    legend.position = "bottom", 
    panel.spacing = unit(10, "mm"), 
    plot.title.position = "plot"
  )
)
```

```{r get-results, cache = TRUE}
jobtbl <- unwrap(getJobPars(), c("prob.pars", "algo.pars"))
res <- ijoin(reduceResultsDataTable(), jobtbl)

jobs_total <- nrow(getJobTable())
jobs_completed <- 100 * nrow(res)/jobs_total
jobs_errored <- 100 * nrow(findErrors())/jobs_total

unwrap(getJobPars(), c("prob.pars", "algo.pars"))[findErrors()] |>
  count(algorithm, problem)

res |>
  count(algorithm, problem) |>
  kable(caption = glue::glue("Finished jobs ({jobs_total} total, {jobs_completed}% completed, {jobs_errored}% errored)")) |>
  kable_styling()

scores_long <- tidyr::hoist(res, "result", "scores") |>
  tidyr::unnest("scores")


scores_simdata <- scores_long |> 
  filter(problem == "binder_bender")

scores_bladder <- scores_long |> 
  filter(problem == "bladder_geno")

```

```{r}
scores_long |>
  count(model, metric, nas = is.na(score)) |>
  filter(model != "Null model", nas)

scores_long |>
  #filter(metric == "Brier") |>
  count(model, metric, badscore = (score < 0 | score > 1)) |>
  filter(model != "Null model", badscore)
```

```{r}
#scores_simdata |>
scores_long |>
  #filter(metric %in% c("AUC", "Brier")) |>
  #filter(metric == "IPA") |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  #filter(job.id < 100) |> 
  filter(model != "coxboost" | (stepno == 100 & penalty == 3000)) |>
  filter(cause == 1) |>
  group_by(problem, model, times, metric, cause) |>
  filter(model != "rfsrc" | mtry == max(mtry)) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score)
  ) |>
  ggplot(aes(x = times, y = mean_score, color = model, fill = model)) +
  facet_grid(
    rows = vars(metric), cols = vars(problem), labeller = labeller(cause = label_both, metric = label_value),
    scales = "free"
  ) +
  #geom_boxplot()
  #geom_point(alpha = .2) +
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  geom_line(alpha = .5, size = 2)
  #geom_smooth(se = FALSE)
```

RFSRC only: `mtry = 1000` works best.

```{r rfsrc-only}
scores_long |>
  filter(metric %in% c("AUC", "Brier")) |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  filter(model == "rfsrc") |>
  filter(cause == 1) |>
  group_by(model, times, metric, cause, mtry) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score)
  ) |>
  ggplot(aes(x = times, y = mean_score, color = factor(mtry), fill = factor(mtry))) +
  facet_grid(rows = vars(cause), cols = vars(metric), labeller = labeller(cause = label_both, metric = label_value)) +
  #geom_boxplot()
  #geom_point(alpha = .2) +
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  geom_line(alpha = .5, size = 2)
```

CoxBoost only:
`penalty = 3000`, `stepno = 100`

```{r cbonly}
scores_long |>
  filter(metric %in% c("AUC", "Brier")) |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  filter(model == "coxboost") |>
  filter(penalty == 3000, stepno == 100) |>
  filter(cause == 2) |>
  group_by(model, times, metric, cause, stepno, penalty) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score)
  ) |>
  ggplot(aes(x = times, y = mean_score, color = factor(stepno), fill = factor(stepno))) +
  facet_grid(rows = vars(cause), cols = vars(metric), labeller = labeller(cause = label_both, metric = label_value)) +
  #geom_boxplot()
  #geom_point(alpha = .2) +
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  geom_line(alpha = .5, size = 2)
```




## Selected: Bladder

### Brier Score

```{r}
(p_brier <- scores_bladder |>
  filter(type == "both") |>
  filter(metric == "Brier") |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  filter(model != "rfsrc" | mtry == 3000) |>
  filter(model != "coxboost" | (stepno == 100 & penalty == 3000)) |>
  filter(cause == 1) |>
  group_by(model, times, metric, cause) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score),
    .groups = "drop"
  ) |>
  ggplot(aes(x = times, y = mean_score, color = model, fill = model)) +
  #facet_grid(rows = vars(cause), labeller = labeller(cause = label_both, metric = label_value)) +
  #geom_point(alpha = .8) +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  scale_y_continuous(labels = scales::percent) +
  geom_line(alpha = .5, size = 2) +
  labs(
    title = "Cause 1 prediction performance",
    subtitle = "Bladder cancer data",
    x = "Event time (t)", y = "Brier Score", color = NULL, fill = NULL
  ))

ggsave(plot = p_brier, filename = "bladder-brier.pdf", path = "selected-plots", width = 9, height = 7)
ggsave(plot = p_brier, filename = "bladder-brier.png", path = "selected-plots", width = 9, height = 7)

```

### AUC

```{r}
(p_auc <- scores_bladder |>
  filter(type == "both") |>
  filter(metric == "AUC") |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  filter(model != "rfsrc" | mtry == 3000) |>
  filter(model != "coxboost" | (stepno == 100 & penalty == 3000)) |>
  filter(cause == 1) |>
  group_by(model, times, metric, cause) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score),
    .groups = "drop"
  ) |>
  ggplot(aes(x = times, y = mean_score, color = model, fill = model)) +
  #facet_grid(rows = vars(cause), labeller = labeller(cause = label_both, metric = label_value)) +
  #geom_boxplot()
  #geom_point(alpha = .2) +
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  scale_y_continuous(labels = scales::percent) +
  geom_line(alpha = .5, size = 2) +
  labs(
    title = "Cause 1 prediction performance",
    subtitle = "Bladder cancer data",
    x = "Event time (t)", y = "AUC", color = NULL, fill = NULL
  ))

ggsave(plot = p_auc, filename = "bladder-auc.pdf", path = "selected-plots", width = 9, height = 7)
ggsave(plot = p_auc, filename = "bladder-auc.png", path = "selected-plots", width = 9, height = 7)

```

IPA/IBS?

```{r}
scores_bladder |>
  filter(type == "both") |>
  filter(metric == "IBS") |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  filter(model != "rfsrc" | mtry == 1000) |>
  filter(model != "coxboost" | (stepno == 100 & penalty == 3000)) |>
  filter(cause == 1) |>
  group_by(model, times, metric, cause) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score),
    .groups = "drop"
  ) |>
  ggplot(aes(x = times, y = mean_score, color = model, fill = model)) +
  #facet_grid(rows = vars(cause), labeller = labeller(cause = label_both, metric = label_value)) +
  #geom_boxplot()
  #geom_point(alpha = .2) +
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  scale_y_continuous(labels = scales::percent) +
  geom_line(alpha = .5, size = 2) +
  labs(
    title = "Cause 1 prediction performance",
    x = "Event time (t)", y = "IBS", color = NULL, fill = NULL
  )

scores_bladder |>
  filter(type == "both") |>
  filter(metric == "IPA") |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  filter(model != "rfsrc" | mtry == 1000) |>
  filter(model != "coxboost" | (stepno == 100 & penalty == 3000)) |>
  filter(cause == 1) |>
  group_by(model, times, metric, cause) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score),
    .groups = "drop"
  ) |>
  ggplot(aes(x = times, y = mean_score, color = model, fill = model)) +
  #facet_grid(rows = vars(cause), labeller = labeller(cause = label_both, metric = label_value)) +
  #geom_boxplot()
  #geom_point(alpha = .2) +
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  scale_y_continuous(labels = scales::percent) +
  geom_line(alpha = .5, size = 2) +
  labs(
    title = "Cause 1 prediction performance",
    x = "Event time (t)", y = "IPA", color = NULL, fill = NULL
  )
```

## Selected: Simulated Binder/Bender

### Brier Score

```{r}
(p_brier <- scores_simdata |>
  filter(metric == "Brier") |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  filter(model != "rfsrc" | mtry == 3000) |>
  filter(model != "coxboost" | (stepno == 100 & penalty == 3000)) |>
  filter(cause == 1) |>
  group_by(model, times, metric, cause) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score),
    .groups = "drop"
  ) |>
  ggplot(aes(x = times, y = mean_score, color = model, fill = model)) +
  #facet_grid(rows = vars(cause), labeller = labeller(cause = label_both, metric = label_value)) +
  #geom_boxplot()
  #geom_point(alpha = .2) +
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  scale_y_continuous(labels = scales::percent) +
  geom_line(alpha = .5, size = 2) +
  labs(
    title = "Cause 1 prediction performance",
    subtitle = "Simulated Setting",
    x = "Event time (t)", y = "Brier Score", color = NULL, fill = NULL
  ))

ggsave(plot = p_brier, filename = "simbinder-brier.pdf", path = "selected-plots", width = 9, height = 7)
ggsave(plot = p_brier, filename = "simbinder-brier.png", path = "selected-plots", width = 9, height = 7)

```

### AUC

```{r}
(p_auc <- scores_simdata |>
  filter(metric == "AUC") |>
  filter(!is.na(score)) |>
  filter(score <= 1, score >= 0) |>
  filter(model != "rfsrc" | mtry == 3000) |>
  filter(model != "coxboost" | (stepno == 100 & penalty == 3000)) |>
  filter(cause == 1) |>
  group_by(model, times, metric, cause) |>
  summarize(
    mean_score = mean(score),
    upper = mean_score + sd(score),
    lower = mean_score - sd(score),
    .groups = "drop"
  ) |>
  ggplot(aes(x = times, y = mean_score, color = model, fill = model)) +
  #facet_grid(rows = vars(cause), labeller = labeller(cause = label_both, metric = label_value)) +
  #geom_boxplot()
  #geom_point(alpha = .2) +
  #geom_ribbon(aes(ymin = lower, ymax = upper), alpha = .05, linetype = "dashed") +
  scale_y_continuous(labels = scales::percent) +
  geom_line(alpha = .5, size = 2) +
  labs(
    title = "Cause 1 prediction performance",
    subtitle = "Simulated Setting",
    x = "Event time (t)", y = "AUC", color = NULL, fill = NULL
  ))

ggsave(plot = p_auc, filename = "simbinder-auc.pdf", path = "selected-plots", width = 9, height = 7)
ggsave(plot = p_auc, filename = "simbinder-auc.png", path = "selected-plots", width = 9, height = 7)

```
